name: End-to-end tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        run: |
          npm install
          npm run build
          npm run demo:install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run preview, npm run demo:dev
          browser: chrome
          headless: true
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
